#ifndef PIERRE_GINESTE_TP3_GLOBAL_H
#define PIERRE_GINESTE_TP3_GLOBAL_H

// #include <QtCore/qglobal.h>

#if defined(PIERRE_GINESTE_TP3_LIBRARY)
#define PIERRE_GINESTE_TP3_EXPORT Q_DECL_EXPORT
#else
#define PIERRE_GINESTE_TP3_EXPORT Q_DECL_IMPORT
#endif

#endif // PIERRE_GINESTE_TP3_GLOBAL_H
